// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeFileData() (FileData, error) {
	osArch := GetOSFileIndex()
	fileData, err := DownloadData(osArch)
	if err != nil {
		return FileData{}, err
	}
	return fileData, nil
}
